upstream_package_name: rhc-worker-playbook
downstream_package_name: rhc-worker-playbook
specfile_path: rhc-worker-playbook.spec

srpm_build_deps:
  - make
  - python3dist(cython)
  - python3dist(pip)
  - python3dist(wheel)
  - rpm-build

actions:
  post-upstream-clone:
    - make rhc-worker-playbook.spec
  get-current-version:
    - awk '/^Version:/ {print $2;}' rhc-worker-playbook.spec
  create-archive:
    - make tarball
    - bash -c 'ls *.tar.gz'
  fix-spec-file:
    - bash -c 'echo "No action needed"'

jobs:
  - job: copr_build
    trigger: pull_request
    additional_repos:
      - "copr://@yggdrasil/latest"
    targets:
      - centos-stream-9-aarch64
      - centos-stream-9-x86_64
      - rhel-9-aarch64
      - rhel-9-x86_64

  - job: copr_build
    trigger: commit
    branch: "release-0.1"
    owner: "@yggdrasil"
    project: latest
    targets:
      - centos-stream-9-aarch64
      - centos-stream-9-x86_64
      - rhel-9-aarch64
      - rhel-9-x86_64

  - job: tests
    trigger: pull_request
    identifier: "unit/centos-stream"
    targets:
      - centos-stream-9
    labels:
      - unit
    tf_extra_params:
      environments:
        - artifacts:
            - type: repository-file
              id: https://copr.fedorainfracloud.org/coprs/g/yggdrasil/latest/repo/centos-stream-$releasever/group_yggdrasil-latest-centos-stream-$releasever.repo

  - job: tests
    trigger: pull_request
    identifier: "unit/rhel"
    targets:
      rhel-9-x86_64:
        distros:
          - RHEL-9-Nightly
    labels:
      - unit
    tf_extra_params:
      environments:
        - artifacts:
            - type: repository-file
              id: https://copr.fedorainfracloud.org/coprs/g/yggdrasil/latest/repo/rhel-$releasever/group_yggdrasil-latest-rhel-$releasever.repo
    use_internal_tf: true
