upstream_package_name: rhc-worker-playbook
downstream_package_name: rhc-worker-playbook
specfile_path: builddir/dist/srpm/rhc-worker-playbook.spec

srpm_build_deps:
  - "pkgconfig(dbus-1)"
  - "pkgconfig(systemd)"
  - "pkgconfig(yggdrasil)"
  - "python3dist(pip)"
  - ansible-core
  - gawk
  - git-core
  - go-rpm-macros
  - golang
  - jq
  - meson
  - rpm-build

actions:
  post-upstream-clone:
    - meson setup builddir -Dbuild_srpm=True -Dvendor=True --wipe
    - meson compile tarball -C builddir
  get-current-version:
    - awk '/^Version:/ {print $2;}' builddir/dist/srpm/rhc-worker-playbook.spec
  create-archive:
    - bash -c 'echo builddir/dist/srpm/rhc-worker-playbook-*.tar.*'
  fix-spec-file:
    - bash -c 'echo "No action needed"'

jobs:
  - job: copr_build
    trigger: pull_request
    additional_repos:
      - "copr://@yggdrasil/latest"
    targets:
      - centos-stream-10-aarch64
      - centos-stream-10-x86_64
      - centos-stream-10-ppc64le
      - centos-stream-10-s390x
      - fedora-all-aarch64
      - fedora-all-x86_64
      - rhel-10-aarch64
      - rhel-10-x86_64
      - rhel-10-ppc64le
      - rhel-10-s390x

  - job: copr_build
    trigger: commit
    branch: main
    owner: "@yggdrasil"
    project: latest
    targets:
      - centos-stream-10-aarch64
      - centos-stream-10-x86_64
      - centos-stream-10-ppc64le
      - centos-stream-10-s390x
      - fedora-all-aarch64
      - fedora-all-x86_64
      - rhel-10-aarch64
      - rhel-10-x86_64
      - rhel-10-ppc64le
      - rhel-10-s390x

  - job: tests
    trigger: pull_request
    identifier: "unit/centos-stream"
    targets:
      - centos-stream-10
    labels:
      - unit
    tf_extra_params:
      environments:
        - artifacts:
            - type: repository-file
              id: https://copr.fedorainfracloud.org/coprs/g/yggdrasil/latest/repo/centos-stream-$releasever/group_yggdrasil-latest-centos-stream-$releasever.repo

  - job: tests
    trigger: pull_request
    identifier: "unit/fedora"
    targets:
      - fedora-all
    labels:
      - unit
    tf_extra_params:
      environments:
        - artifacts:
            - type: repository-file
              id: https://copr.fedorainfracloud.org/coprs/g/yggdrasil/latest/repo/fedora-$releasever/group_yggdrasil-latest-fedora-$releasever.repo

  - job: tests
    trigger: pull_request
    identifier: "unit/rhel"
    targets:
      rhel-10-x86_64:
        distros:
          - RHEL-10-Nightly
    labels:
      - unit
    tf_extra_params:
      environments:
        - artifacts:
            - type: repository-file
              id: https://copr.fedorainfracloud.org/coprs/g/yggdrasil/latest/repo/rhel-$releasever/group_yggdrasil-latest-rhel-$releasever.repo
    use_internal_tf: true
