# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: yggdrasil.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='yggdrasil.proto',
  package='yggdrasil',
  syntax='proto3',
  serialized_options=b'Z,github.com/redhatinsights/yggdrasil/protocol',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0fyggdrasil.proto\x12\tyggdrasil\"\x07\n\x05\x45mpty\"/\n\x0fRegisterRequest\x12\x0f\n\x07handler\x18\x01 \x01(\t\x12\x0b\n\x03pid\x18\x02 \x01(\x03\"G\n\x10RegisterResponse\x12\x12\n\nregistered\x18\x01 \x01(\x08\x12\x0f\n\x07\x61\x64\x64ress\x18\x02 \x01(\t\x12\x0e\n\x06reason\x18\x03 \x01(\t\"\xae\x01\n\nAssignment\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\x12\x10\n\x08\x63omplete\x18\x03 \x01(\x08\x12\x0f\n\x07handler\x18\x04 \x01(\t\x12\x33\n\x07headers\x18\x05 \x03(\x0b\x32\".yggdrasil.Assignment.HeadersEntry\x1a.\n\x0cHeadersEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"!\n\rStartResponse\x12\x10\n\x08\x61\x63\x63\x65pted\x18\x01 \x01(\x08\"]\n\x0cWorkerStatus\x12.\n\x06status\x18\x01 \x01(\x0e\x32\x1e.yggdrasil.WorkerStatus.Status\"\x1d\n\x06Status\x12\t\n\x05READY\x10\x00\x12\x08\n\x04\x42USY\x10\x01\x32\xbd\x01\n\nDispatcher\x12\x45\n\x08Register\x12\x1a.yggdrasil.RegisterRequest\x1a\x1b.yggdrasil.RegisterResponse\"\x00\x12\x33\n\x06Update\x12\x15.yggdrasil.Assignment\x1a\x10.yggdrasil.Empty\"\x00\x12\x33\n\x06\x46inish\x12\x15.yggdrasil.Assignment\x1a\x10.yggdrasil.Empty\"\x00\x32{\n\x06Worker\x12:\n\x05Start\x12\x15.yggdrasil.Assignment\x1a\x18.yggdrasil.StartResponse\"\x00\x12\x35\n\x06Status\x12\x10.yggdrasil.Empty\x1a\x17.yggdrasil.WorkerStatus\"\x00\x42.Z,github.com/redhatinsights/yggdrasil/protocolb\x06proto3'
)



_WORKERSTATUS_STATUS = _descriptor.EnumDescriptor(
  name='Status',
  full_name='yggdrasil.WorkerStatus.Status',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='READY', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='BUSY', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=437,
  serialized_end=466,
)
_sym_db.RegisterEnumDescriptor(_WORKERSTATUS_STATUS)


_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='yggdrasil.Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=37,
)


_REGISTERREQUEST = _descriptor.Descriptor(
  name='RegisterRequest',
  full_name='yggdrasil.RegisterRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='handler', full_name='yggdrasil.RegisterRequest.handler', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pid', full_name='yggdrasil.RegisterRequest.pid', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=39,
  serialized_end=86,
)


_REGISTERRESPONSE = _descriptor.Descriptor(
  name='RegisterResponse',
  full_name='yggdrasil.RegisterResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='registered', full_name='yggdrasil.RegisterResponse.registered', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='address', full_name='yggdrasil.RegisterResponse.address', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='reason', full_name='yggdrasil.RegisterResponse.reason', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=88,
  serialized_end=159,
)


_ASSIGNMENT_HEADERSENTRY = _descriptor.Descriptor(
  name='HeadersEntry',
  full_name='yggdrasil.Assignment.HeadersEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='yggdrasil.Assignment.HeadersEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='yggdrasil.Assignment.HeadersEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=290,
  serialized_end=336,
)

_ASSIGNMENT = _descriptor.Descriptor(
  name='Assignment',
  full_name='yggdrasil.Assignment',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='yggdrasil.Assignment.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data', full_name='yggdrasil.Assignment.data', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='complete', full_name='yggdrasil.Assignment.complete', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='handler', full_name='yggdrasil.Assignment.handler', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='headers', full_name='yggdrasil.Assignment.headers', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_ASSIGNMENT_HEADERSENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=162,
  serialized_end=336,
)


_STARTRESPONSE = _descriptor.Descriptor(
  name='StartResponse',
  full_name='yggdrasil.StartResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='accepted', full_name='yggdrasil.StartResponse.accepted', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=338,
  serialized_end=371,
)


_WORKERSTATUS = _descriptor.Descriptor(
  name='WorkerStatus',
  full_name='yggdrasil.WorkerStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='yggdrasil.WorkerStatus.status', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _WORKERSTATUS_STATUS,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=373,
  serialized_end=466,
)

_ASSIGNMENT_HEADERSENTRY.containing_type = _ASSIGNMENT
_ASSIGNMENT.fields_by_name['headers'].message_type = _ASSIGNMENT_HEADERSENTRY
_WORKERSTATUS.fields_by_name['status'].enum_type = _WORKERSTATUS_STATUS
_WORKERSTATUS_STATUS.containing_type = _WORKERSTATUS
DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
DESCRIPTOR.message_types_by_name['RegisterRequest'] = _REGISTERREQUEST
DESCRIPTOR.message_types_by_name['RegisterResponse'] = _REGISTERRESPONSE
DESCRIPTOR.message_types_by_name['Assignment'] = _ASSIGNMENT
DESCRIPTOR.message_types_by_name['StartResponse'] = _STARTRESPONSE
DESCRIPTOR.message_types_by_name['WorkerStatus'] = _WORKERSTATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'yggdrasil_pb2'
  # @@protoc_insertion_point(class_scope:yggdrasil.Empty)
  })
_sym_db.RegisterMessage(Empty)

RegisterRequest = _reflection.GeneratedProtocolMessageType('RegisterRequest', (_message.Message,), {
  'DESCRIPTOR' : _REGISTERREQUEST,
  '__module__' : 'yggdrasil_pb2'
  # @@protoc_insertion_point(class_scope:yggdrasil.RegisterRequest)
  })
_sym_db.RegisterMessage(RegisterRequest)

RegisterResponse = _reflection.GeneratedProtocolMessageType('RegisterResponse', (_message.Message,), {
  'DESCRIPTOR' : _REGISTERRESPONSE,
  '__module__' : 'yggdrasil_pb2'
  # @@protoc_insertion_point(class_scope:yggdrasil.RegisterResponse)
  })
_sym_db.RegisterMessage(RegisterResponse)

Assignment = _reflection.GeneratedProtocolMessageType('Assignment', (_message.Message,), {

  'HeadersEntry' : _reflection.GeneratedProtocolMessageType('HeadersEntry', (_message.Message,), {
    'DESCRIPTOR' : _ASSIGNMENT_HEADERSENTRY,
    '__module__' : 'yggdrasil_pb2'
    # @@protoc_insertion_point(class_scope:yggdrasil.Assignment.HeadersEntry)
    })
  ,
  'DESCRIPTOR' : _ASSIGNMENT,
  '__module__' : 'yggdrasil_pb2'
  # @@protoc_insertion_point(class_scope:yggdrasil.Assignment)
  })
_sym_db.RegisterMessage(Assignment)
_sym_db.RegisterMessage(Assignment.HeadersEntry)

StartResponse = _reflection.GeneratedProtocolMessageType('StartResponse', (_message.Message,), {
  'DESCRIPTOR' : _STARTRESPONSE,
  '__module__' : 'yggdrasil_pb2'
  # @@protoc_insertion_point(class_scope:yggdrasil.StartResponse)
  })
_sym_db.RegisterMessage(StartResponse)

WorkerStatus = _reflection.GeneratedProtocolMessageType('WorkerStatus', (_message.Message,), {
  'DESCRIPTOR' : _WORKERSTATUS,
  '__module__' : 'yggdrasil_pb2'
  # @@protoc_insertion_point(class_scope:yggdrasil.WorkerStatus)
  })
_sym_db.RegisterMessage(WorkerStatus)


DESCRIPTOR._options = None
_ASSIGNMENT_HEADERSENTRY._options = None

_DISPATCHER = _descriptor.ServiceDescriptor(
  name='Dispatcher',
  full_name='yggdrasil.Dispatcher',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=469,
  serialized_end=658,
  methods=[
  _descriptor.MethodDescriptor(
    name='Register',
    full_name='yggdrasil.Dispatcher.Register',
    index=0,
    containing_service=None,
    input_type=_REGISTERREQUEST,
    output_type=_REGISTERRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Update',
    full_name='yggdrasil.Dispatcher.Update',
    index=1,
    containing_service=None,
    input_type=_ASSIGNMENT,
    output_type=_EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Finish',
    full_name='yggdrasil.Dispatcher.Finish',
    index=2,
    containing_service=None,
    input_type=_ASSIGNMENT,
    output_type=_EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_DISPATCHER)

DESCRIPTOR.services_by_name['Dispatcher'] = _DISPATCHER


_WORKER = _descriptor.ServiceDescriptor(
  name='Worker',
  full_name='yggdrasil.Worker',
  file=DESCRIPTOR,
  index=1,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=660,
  serialized_end=783,
  methods=[
  _descriptor.MethodDescriptor(
    name='Start',
    full_name='yggdrasil.Worker.Start',
    index=0,
    containing_service=None,
    input_type=_ASSIGNMENT,
    output_type=_STARTRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Status',
    full_name='yggdrasil.Worker.Status',
    index=1,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_WORKERSTATUS,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_WORKER)

DESCRIPTOR.services_by_name['Worker'] = _WORKER

# @@protoc_insertion_point(module_scope)
